onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /cpu_TB/UUT/Clk
add wave -noupdate /cpu_TB/UUT/Reset_N
add wave -noupdate /cpu_TB/UUT/readM1
add wave -noupdate /cpu_TB/UUT/address1
add wave -noupdate /cpu_TB/UUT/readM2
add wave -noupdate /cpu_TB/UUT/writeM2
add wave -noupdate /cpu_TB/UUT/address2
add wave -noupdate /cpu_TB/UUT/data1
add wave -noupdate /cpu_TB/UUT/data2
add wave -noupdate /cpu_TB/UUT/read_ack
add wave -noupdate /cpu_TB/UUT/write_ack
add wave -noupdate /cpu_TB/UUT/mem_fetch_owner
add wave -noupdate /cpu_TB/UUT/num_inst
add wave -noupdate /cpu_TB/UUT/output_port
add wave -noupdate /cpu_TB/UUT/is_halted
add wave -noupdate /cpu_TB/UUT/inst_output
add wave -noupdate /cpu_TB/UUT/pc_num_inst
add wave -noupdate /cpu_TB/UUT/pc
add wave -noupdate /cpu_TB/UUT/next_pc
add wave -noupdate /cpu_TB/UUT/pred_pc
add wave -noupdate /cpu_TB/UUT/jtype_jump
add wave -noupdate /cpu_TB/UUT/flush
add wave -noupdate /cpu_TB/UUT/id_ex_jtype_jump
add wave -noupdate /cpu_TB/UUT/target
add wave -noupdate /cpu_TB/UUT/is_inst_hit
add wave -noupdate /cpu_TB/UUT/is_stall
add wave -noupdate -expand /cpu_TB/UUT/DATA_CACHE/data_bank
add wave -noupdate /cpu_TB/UUT/bcond
add wave -noupdate /cpu_TB/UUT/before_if_stall
add wave -noupdate /cpu_TB/UUT/stall_before_mem
add wave -noupdate /cpu_TB/UUT/A
add wave -noupdate /cpu_TB/UUT/B
add wave -noupdate /cpu_TB/UUT/C
add wave -noupdate /cpu_TB/UUT/sign_extended_imm
add wave -noupdate /cpu_TB/UUT/rs
add wave -noupdate /cpu_TB/UUT/rt
add wave -noupdate /cpu_TB/UUT/ex_mem_wb
add wave -noupdate /cpu_TB/UUT/wb
add wave -noupdate /cpu_TB/UUT/read_out1
add wave -noupdate /cpu_TB/UUT/read_out2
add wave -noupdate /cpu_TB/UUT/mem_write
add wave -noupdate /cpu_TB/UUT/mem_read
add wave -noupdate -expand -group data /cpu_TB/UUT/ex_mem_alu_result
add wave -noupdate -expand -group data /cpu_TB/UUT/ex_mem_mem_write
add wave -noupdate -expand -group data /cpu_TB/UUT/ex_mem_mem_read
add wave -noupdate -expand -group data /cpu_TB/UUT/data_req
add wave -noupdate -expand -group data /cpu_TB/UUT/ex_mem_read_out2
add wave -noupdate -expand -group data /cpu_TB/UUT/is_data_hit
add wave -noupdate /cpu_TB/UUT/id_ex_mem_write
add wave -noupdate /cpu_TB/UUT/id_ex_mem_read
add wave -noupdate /cpu_TB/UUT/reg_write
add wave -noupdate /cpu_TB/UUT/mem_to_reg
add wave -noupdate /cpu_TB/UUT/pc_to_reg
add wave -noupdate /cpu_TB/UUT/is_wwd
add wave -noupdate /cpu_TB/UUT/is_cur_inst_halted
add wave -noupdate /cpu_TB/UUT/rtype_jump
add wave -noupdate /cpu_TB/UUT/branch
add wave -noupdate /cpu_TB/UUT/alu_src
add wave -noupdate /cpu_TB/UUT/reg_dest
add wave -noupdate /cpu_TB/UUT/alu_op
add wave -noupdate /cpu_TB/UUT/forwardA
add wave -noupdate /cpu_TB/UUT/forwardB
add wave -noupdate /cpu_TB/UUT/pred_taken
add wave -noupdate /cpu_TB/UUT/btb_target
add wave -noupdate /cpu_TB/UUT/inst_mem_read_req
add wave -noupdate /cpu_TB/UUT/inst_mem_write_req
add wave -noupdate /cpu_TB/UUT/inst_read_address
add wave -noupdate /cpu_TB/UUT/inst_write_address
add wave -noupdate /cpu_TB/UUT/inst_mem_fetch_output
add wave -noupdate /cpu_TB/UUT/data_mem_read_req
add wave -noupdate /cpu_TB/UUT/data_mem_write_req
add wave -noupdate /cpu_TB/UUT/data_read_address
add wave -noupdate /cpu_TB/UUT/data_write_address
add wave -noupdate /cpu_TB/UUT/data_mem_fetch_output
add wave -noupdate /cpu_TB/UUT/stall_if
add wave -noupdate /cpu_TB/UUT/rest
add wave -noupdate /cpu_TB/UUT/instruction_fetech
add wave -noupdate /cpu_TB/UUT/if_id_num_inst
add wave -noupdate /cpu_TB/UUT/id_ex_num_inst
add wave -noupdate /cpu_TB/UUT/ex_mem_num_inst
add wave -noupdate /cpu_TB/UUT/mem_wb_num_inst
add wave -noupdate /cpu_TB/UUT/output_num_inst
add wave -noupdate /cpu_TB/UUT/id_ex_jump_target_addr
add wave -noupdate /cpu_TB/UUT/if_id_pc
add wave -noupdate /cpu_TB/UUT/id_ex_pred_pc
add wave -noupdate /cpu_TB/UUT/id_ex_pc
add wave -noupdate /cpu_TB/UUT/if_id_pc_plus_one
add wave -noupdate /cpu_TB/UUT/id_ex_pc_plus_one
add wave -noupdate /cpu_TB/UUT/ex_mem_pc_plus_one
add wave -noupdate /cpu_TB/UUT/mem_wb_pc_plus_one
add wave -noupdate /cpu_TB/UUT/id_ex_opcode
add wave -noupdate /cpu_TB/UUT/if_id_instruction
add wave -noupdate /cpu_TB/UUT/id_ex_alu_src
add wave -noupdate /cpu_TB/UUT/id_ex_reg_dest
add wave -noupdate /cpu_TB/UUT/id_ex_alu_op
add wave -noupdate /cpu_TB/UUT/id_ex_pc_to_reg
add wave -noupdate /cpu_TB/UUT/ex_mem_pc_to_reg
add wave -noupdate /cpu_TB/UUT/mem_wb_pc_to_reg
add wave -noupdate /cpu_TB/UUT/id_ex_is_wwd
add wave -noupdate /cpu_TB/UUT/ex_mem_is_wwd
add wave -noupdate /cpu_TB/UUT/mem_wb_is_wwd
add wave -noupdate /cpu_TB/UUT/id_ex_is_halted
add wave -noupdate /cpu_TB/UUT/ex_mem_is_halted
add wave -noupdate /cpu_TB/UUT/mem_wb_is_halted
add wave -noupdate /cpu_TB/UUT/id_ex_branch
add wave -noupdate /cpu_TB/UUT/id_ex_rtype_jump
add wave -noupdate /cpu_TB/UUT/id_ex_reg_write
add wave -noupdate /cpu_TB/UUT/id_ex_mem_to_reg
add wave -noupdate /cpu_TB/UUT/ex_mem_reg_write
add wave -noupdate /cpu_TB/UUT/ex_mem_mem_to_reg
add wave -noupdate /cpu_TB/UUT/mem_wb_reg_write
add wave -noupdate /cpu_TB/UUT/mem_wb_mem_to_reg
add wave -noupdate /cpu_TB/UUT/id_ex_sign_extended_imm
add wave -noupdate /cpu_TB/UUT/id_ex_rd
add wave -noupdate /cpu_TB/UUT/id_ex_rt
add wave -noupdate /cpu_TB/UUT/id_ex_rs
add wave -noupdate /cpu_TB/UUT/ex_mem_dest
add wave -noupdate /cpu_TB/UUT/mem_wb_dest
add wave -noupdate /cpu_TB/UUT/mem_wb_alu_result
add wave -noupdate /cpu_TB/UUT/ex_mem_A
add wave -noupdate /cpu_TB/UUT/mem_wb_A
add wave -noupdate /cpu_TB/UUT/id_ex_read_out1
add wave -noupdate /cpu_TB/UUT/id_ex_read_out2
add wave -noupdate /cpu_TB/UUT/mem_wb_read_data
add wave -noupdate /cpu_TB/UUT/if_id_pred_pc
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {42897 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 283
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {69471 ns} {72291 ns}
